#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Author: Jonas Borgström <jonas@edgewall.com>
#
# This script will enforce the following policy:
#
#  "A checkin must reference an open ticket."
#
# This script should be invoked from the subversion pre-commit hook like this:
#
#  REPOS="$1"
#  TXN="$2"
#  TRAC_ENV="/somewhere/trac/project/"
#  LOG=`/usr/bin/svnlook log -t "$TXN" "$REPOS"`
#  /usr/bin/python /some/path/trac-pre-commit-hook "$TRAC_ENV" "$LOG" || exit 1
#
import os
import re
import sys

import popen2
import fcntl
import select
import string
import subprocess


if not 'PYTHON_EGG_CACHE' in os.environ:
    os.environ['PYTHON_EGG_CACHE'] = os.path.join(sys.argv[1], '.egg-cache') 

from trac.env import open_environment

def verifica_msglog(log):
    achou=re.match('(Ticket #[0-9]{1,6} - )',log)
    if achou:
		verificatamanho=re.match('Ticket #[0-9]{1,6} - {0,3}.{40,100}$',log)
		if verificatamanho:
			return (0)
		else:
			sys.stderr.write ("\nRESPEITE O TAMANHO DA DESCRICAO. DEVE SER ENTRE 40 E 100 CARACTERES!\n")
	    	return (1)
    else:
       	sys.stderr.write ("\nRESPEITE O FORMATO DO COMENTARIO: Ticket #000 - <Descricao de 40 a 100 caracteres>.\n")
       	return (1)


def main():
    if len(sys.argv) != 3:
        print >> sys.stderr, 'Usage: %s <trac_project> <log_message>' % sys.argv[0]
        sys.exit(1)

    env_path = sys.argv[1]
    log = sys.argv[2]

#    args = sys.argv[3] + sys.argv[4]
#    pipe = subprocess.Popen(["sys.argv[3]/hooks/pre-commit.pl", args], shell=True, executable="/usr/bin/perl")
    
    tickets = []
    for tmp in re.findall('(?:close|closed|closes|fix|fixed|fixes|addresses|references|refs|re|see|ticket)'
                          '.?(#[0-9]+(?:(?:[, &]+| *and *)#[0-9]+)*)', log.lower()):
        tickets += re.findall('#([0-9]+)', tmp)
   
    if verifica_msglog(log):
        sys.exit(1)

    # At least one ticket has to be mentioned in the log message
    if tickets == []:
        print >> sys.stderr, "Pelo menos um ticket _aberto_ no trac deve ser mencionado " \
              'na mensagem de log.'
        sys.exit(1)

    env = open_environment(env_path)
    db = env.get_db_cnx()

    cursor = db.cursor()
    cursor.execute("SELECT COUNT(id) FROM ticket WHERE "
                   "status <> 'closed' AND id IN (%s)" % ','.join(tickets))
    row = cursor.fetchone()
    # At least one of the tickets mentioned in the log messages has to
    # be open
    if not row or row[0] < 1:
        print >> sys.stderr, 'Pelo menos um ticket _aberto_ no trac deve ser mencionado ' \
              'na mensagem de log.'
        sys.exit(1)
    else:
        sys.exit(0)

if __name__ == '__main__':
    main()


if __name__ == '__main__':
    if len(sys.argv) < 3:
        sys.stderr.write("Usage: %s REPOS TXN\n" % (sys.argv[0]))
    else:
        main(sys.argv[1], sys.argv[2])
